var annotated_dup =
[
    [ "What is SipaaKernel?", "md_README.html#autotoc_md0", null ],
    [ "Features & Todo", "md_README.html#autotoc_md1", [
      [ "What does it mean?", "md_README.html#autotoc_md2", null ],
      [ "x86_64 architecture (src/kernel/arch/x86_64)", "md_README.html#autotoc_md3", null ],
      [ "i686 architecture (src/kernel/arch/i686)", "md_README.html#autotoc_md4", null ],
      [ "AArch64 (src/kernel/sk-aarch64)", "md_README.html#autotoc_md5", null ],
      [ "Kernel (src/kernel/sk-core)", "md_README.html#autotoc_md6", null ],
      [ "Kernel (in User Mode)", "md_README.html#autotoc_md7", null ],
      [ "Devices (src/kernel/sk-dev)", "md_README.html#autotoc_md8", null ]
    ] ],
    [ "How to build SipaaKernel?", "md_README.html#autotoc_md9", [
      [ "Step 1 : Install the dependencies", "md_README.html#autotoc_md10", [
        [ "On Arch Linux", "md_README.html#autotoc_md11", null ]
      ] ],
      [ "Step 2 : Build & Boot SipaaKernel", "md_README.html#autotoc_md12", null ]
    ] ],
    [ "Q&A", "md_README.html#autotoc_md13", [
      [ "Why chosing CuteKit?", "md_README.html#autotoc_md14", null ],
      [ "Will it have a desktop environment & apps?", "md_README.html#autotoc_md15", null ]
    ] ],
    [ "Credits", "md_README.html#autotoc_md16", null ],
    [ "__attribute__", "struct____attribute____.html", "struct____attribute____" ],
    [ "Builder", "classBuilder.html", "classBuilder" ],
    [ "BuildOptions", "classBuildOptions.html", "classBuildOptions" ],
    [ "CleanOptions", "classCleanOptions.html", null ],
    [ "ConfigureOptions", "classConfigureOptions.html", null ],
    [ "Constants", "classConstants.html", "classConstants" ],
    [ "DeviceDriversWindow", "classDeviceDriversWindow.html", "classDeviceDriversWindow" ],
    [ "DoctorCommentProvider", "classDoctorCommentProvider.html", "classDoctorCommentProvider" ],
    [ "DoctorOptions", "classDoctorOptions.html", "classDoctorOptions" ],
    [ "flanterm_context", "structflanterm__context.html", "structflanterm__context" ],
    [ "flanterm_fb_char", "structflanterm__fb__char.html", "structflanterm__fb__char" ],
    [ "flanterm_fb_context", "structflanterm__fb__context.html", "structflanterm__fb__context" ],
    [ "flanterm_fb_queue_item", "structflanterm__fb__queue__item.html", "structflanterm__fb__queue__item" ],
    [ "GeneralWindow", "classGeneralWindow.html", "classGeneralWindow" ],
    [ "interrupt_frame", "structinterrupt__frame.html", "structinterrupt__frame" ],
    [ "IOUtils", "classIOUtils.html", "classIOUtils" ],
    [ "key_choice", "structkey__choice.html", "structkey__choice" ],
    [ "limine_5_level_paging_request", "structlimine__5__level__paging__request.html", "structlimine__5__level__paging__request" ],
    [ "limine_5_level_paging_response", "structlimine__5__level__paging__response.html", "structlimine__5__level__paging__response" ],
    [ "limine_boot_time_request", "structlimine__boot__time__request.html", "structlimine__boot__time__request" ],
    [ "limine_boot_time_response", "structlimine__boot__time__response.html", "structlimine__boot__time__response" ],
    [ "limine_bootloader_info_request", "structlimine__bootloader__info__request.html", "structlimine__bootloader__info__request" ],
    [ "limine_bootloader_info_response", "structlimine__bootloader__info__response.html", "structlimine__bootloader__info__response" ],
    [ "limine_dtb_request", "structlimine__dtb__request.html", "structlimine__dtb__request" ],
    [ "limine_dtb_response", "structlimine__dtb__response.html", "structlimine__dtb__response" ],
    [ "limine_efi_memmap_request", "structlimine__efi__memmap__request.html", "structlimine__efi__memmap__request" ],
    [ "limine_efi_memmap_response", "structlimine__efi__memmap__response.html", "structlimine__efi__memmap__response" ],
    [ "limine_efi_system_table_request", "structlimine__efi__system__table__request.html", "structlimine__efi__system__table__request" ],
    [ "limine_efi_system_table_response", "structlimine__efi__system__table__response.html", "structlimine__efi__system__table__response" ],
    [ "limine_entry_point_request", "structlimine__entry__point__request.html", "structlimine__entry__point__request" ],
    [ "limine_entry_point_response", "structlimine__entry__point__response.html", "structlimine__entry__point__response" ],
    [ "limine_file", "structlimine__file.html", "structlimine__file" ],
    [ "limine_framebuffer", "structlimine__framebuffer.html", "structlimine__framebuffer" ],
    [ "limine_framebuffer_request", "structlimine__framebuffer__request.html", "structlimine__framebuffer__request" ],
    [ "limine_framebuffer_response", "structlimine__framebuffer__response.html", "structlimine__framebuffer__response" ],
    [ "limine_hhdm_request", "structlimine__hhdm__request.html", "structlimine__hhdm__request" ],
    [ "limine_hhdm_response", "structlimine__hhdm__response.html", "structlimine__hhdm__response" ],
    [ "limine_internal_module", "structlimine__internal__module.html", "structlimine__internal__module" ],
    [ "limine_kernel_address_request", "structlimine__kernel__address__request.html", "structlimine__kernel__address__request" ],
    [ "limine_kernel_address_response", "structlimine__kernel__address__response.html", "structlimine__kernel__address__response" ],
    [ "limine_kernel_file_request", "structlimine__kernel__file__request.html", "structlimine__kernel__file__request" ],
    [ "limine_kernel_file_response", "structlimine__kernel__file__response.html", "structlimine__kernel__file__response" ],
    [ "limine_memmap_entry", "structlimine__memmap__entry.html", "structlimine__memmap__entry" ],
    [ "limine_memmap_request", "structlimine__memmap__request.html", "structlimine__memmap__request" ],
    [ "limine_memmap_response", "structlimine__memmap__response.html", "structlimine__memmap__response" ],
    [ "limine_module_request", "structlimine__module__request.html", "structlimine__module__request" ],
    [ "limine_module_response", "structlimine__module__response.html", "structlimine__module__response" ],
    [ "limine_paging_mode_request", "structlimine__paging__mode__request.html", "structlimine__paging__mode__request" ],
    [ "limine_paging_mode_response", "structlimine__paging__mode__response.html", "structlimine__paging__mode__response" ],
    [ "limine_rsdp_request", "structlimine__rsdp__request.html", "structlimine__rsdp__request" ],
    [ "limine_rsdp_response", "structlimine__rsdp__response.html", "structlimine__rsdp__response" ],
    [ "limine_smbios_request", "structlimine__smbios__request.html", "structlimine__smbios__request" ],
    [ "limine_smbios_response", "structlimine__smbios__response.html", "structlimine__smbios__response" ],
    [ "limine_smp_request", "structlimine__smp__request.html", "structlimine__smp__request" ],
    [ "limine_stack_size_request", "structlimine__stack__size__request.html", "structlimine__stack__size__request" ],
    [ "limine_stack_size_response", "structlimine__stack__size__response.html", "structlimine__stack__size__response" ],
    [ "limine_terminal", "structlimine__terminal.html", "structlimine__terminal" ],
    [ "limine_terminal_request", "structlimine__terminal__request.html", "structlimine__terminal__request" ],
    [ "limine_terminal_response", "structlimine__terminal__response.html", "structlimine__terminal__response" ],
    [ "limine_uuid", "structlimine__uuid.html", "structlimine__uuid" ],
    [ "limine_video_mode", "structlimine__video__mode.html", "structlimine__video__mode" ],
    [ "MainFrame", "classMainFrame.html", "classMainFrame" ],
    [ "multiboot_aout_symbol_table", "structmultiboot__aout__symbol__table.html", "structmultiboot__aout__symbol__table" ],
    [ "multiboot_apm_info", "structmultiboot__apm__info.html", "structmultiboot__apm__info" ],
    [ "multiboot_color", "structmultiboot__color.html", "structmultiboot__color" ],
    [ "multiboot_elf_section_header_table", "structmultiboot__elf__section__header__table.html", "structmultiboot__elf__section__header__table" ],
    [ "multiboot_header", "structmultiboot__header.html", "structmultiboot__header" ],
    [ "multiboot_header_tag", "structmultiboot__header__tag.html", "structmultiboot__header__tag" ],
    [ "multiboot_header_tag_address", "structmultiboot__header__tag__address.html", "structmultiboot__header__tag__address" ],
    [ "multiboot_header_tag_console_flags", "structmultiboot__header__tag__console__flags.html", "structmultiboot__header__tag__console__flags" ],
    [ "multiboot_header_tag_entry_address", "structmultiboot__header__tag__entry__address.html", "structmultiboot__header__tag__entry__address" ],
    [ "multiboot_header_tag_framebuffer", "structmultiboot__header__tag__framebuffer.html", "structmultiboot__header__tag__framebuffer" ],
    [ "multiboot_header_tag_information_request", "structmultiboot__header__tag__information__request.html", "structmultiboot__header__tag__information__request" ],
    [ "multiboot_header_tag_module_align", "structmultiboot__header__tag__module__align.html", "structmultiboot__header__tag__module__align" ],
    [ "multiboot_header_tag_relocatable", "structmultiboot__header__tag__relocatable.html", "structmultiboot__header__tag__relocatable" ],
    [ "multiboot_info", "structmultiboot__info.html", "structmultiboot__info" ],
    [ "multiboot_mmap_entry", "structmultiboot__mmap__entry.html", "structmultiboot__mmap__entry" ],
    [ "multiboot_mod_list", "structmultiboot__mod__list.html", "structmultiboot__mod__list" ],
    [ "multiboot_tag", "structmultiboot__tag.html", "structmultiboot__tag" ],
    [ "multiboot_tag_apm", "structmultiboot__tag__apm.html", "structmultiboot__tag__apm" ],
    [ "multiboot_tag_basic_meminfo", "structmultiboot__tag__basic__meminfo.html", "structmultiboot__tag__basic__meminfo" ],
    [ "multiboot_tag_bootdev", "structmultiboot__tag__bootdev.html", "structmultiboot__tag__bootdev" ],
    [ "multiboot_tag_efi32", "structmultiboot__tag__efi32.html", "structmultiboot__tag__efi32" ],
    [ "multiboot_tag_efi32_ih", "structmultiboot__tag__efi32__ih.html", "structmultiboot__tag__efi32__ih" ],
    [ "multiboot_tag_efi64", "structmultiboot__tag__efi64.html", "structmultiboot__tag__efi64" ],
    [ "multiboot_tag_efi64_ih", "structmultiboot__tag__efi64__ih.html", "structmultiboot__tag__efi64__ih" ],
    [ "multiboot_tag_efi_mmap", "structmultiboot__tag__efi__mmap.html", "structmultiboot__tag__efi__mmap" ],
    [ "multiboot_tag_elf_sections", "structmultiboot__tag__elf__sections.html", "structmultiboot__tag__elf__sections" ],
    [ "multiboot_tag_framebuffer", "structmultiboot__tag__framebuffer.html", "structmultiboot__tag__framebuffer" ],
    [ "multiboot_tag_framebuffer_common", "structmultiboot__tag__framebuffer__common.html", "structmultiboot__tag__framebuffer__common" ],
    [ "multiboot_tag_load_base_addr", "structmultiboot__tag__load__base__addr.html", "structmultiboot__tag__load__base__addr" ],
    [ "multiboot_tag_mmap", "structmultiboot__tag__mmap.html", "structmultiboot__tag__mmap" ],
    [ "multiboot_tag_module", "structmultiboot__tag__module.html", "structmultiboot__tag__module" ],
    [ "multiboot_tag_network", "structmultiboot__tag__network.html", "structmultiboot__tag__network" ],
    [ "multiboot_tag_new_acpi", "structmultiboot__tag__new__acpi.html", "structmultiboot__tag__new__acpi" ],
    [ "multiboot_tag_old_acpi", "structmultiboot__tag__old__acpi.html", "structmultiboot__tag__old__acpi" ],
    [ "multiboot_tag_smbios", "structmultiboot__tag__smbios.html", "structmultiboot__tag__smbios" ],
    [ "multiboot_tag_string", "structmultiboot__tag__string.html", "structmultiboot__tag__string" ],
    [ "multiboot_tag_vbe", "structmultiboot__tag__vbe.html", "structmultiboot__tag__vbe" ],
    [ "multiboot_vbe_info_block", "structmultiboot__vbe__info__block.html", "structmultiboot__vbe__info__block" ],
    [ "multiboot_vbe_mode_info_block", "structmultiboot__vbe__mode__info__block.html", "structmultiboot__vbe__mode__info__block" ],
    [ "Program", "classProgram.html", "classProgram" ],
    [ "sk_framebuffer", "structsk__framebuffer.html", "structsk__framebuffer" ],
    [ "sk_general_boot_info", "structsk__general__boot__info.html", "structsk__general__boot__info" ],
    [ "sk_memory_info", "structsk__memory__info.html", "structsk__memory__info" ],
    [ "sk_memory_mapentry", "structsk__memory__mapentry.html", "structsk__memory__mapentry" ],
    [ "SKConfig", "classSKConfig.html", "classSKConfig" ],
    [ "system_interface", "structsystem__interface.html", null ]
];